#!/bin/bash

# Check if the repository name is provided
if [ -z "$1" ]; then
  echo "Error: Repository name is required."
  echo "Usage:
repoList <repository_name>(format : username/repository_name) {for lisiting packages in a repository}

sudo repoList <repository_name>(format : username/repository_name) {for lisiting packages and enabling the repository as well}"
  exit 1
fi

# Check if the repository is enabled
if ! dnf copr list | grep -q "$1"; then
  # Enable the repository if it's not already enabled
  sudo dnf copr enable "$1" || { echo "Failed to enable repository"; exit 1; }
fi

# List all packages in the repository
copr list-packages "$1" | jq -r '.[] | .name'
